name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_ssh:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - host: 1.bj.aliyun.bonjour.zone
            pubkey: AAAAC3NzaC1lZDI1NTE5AAAAIFij2QuvS/uuJh9/8DhMLPl50eTeWixEGEb9oHwBKjba
    steps:
      - name: Make ssh directory
        run: mkdir ~/.ssh 
      - name: Configure ssh known_hosts
        run: echo '${{ matrix.host }} ssh-ed25519 ${{ matrix.pubkey }}' >> ~/.ssh/known_hosts
      - name: Configure ssh private key
        run: echo '${{ secrets.SSH_KEY }}' >> ~/.ssh/id_ed25519; chmod u=rw,go= ~/.ssh/id_ed25519
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Make secrets directory
        run: mkdir secrets
      - name: Configure secrets ALIYUN_OSS
        run: echo '${{ secrets.ALIYUN_OSS }}' >> secrets/aliyun_oss; chmod u=rw,go= secrets/aliyun_oss
      - name: Configure service ADMIN_TOKEN
        run: sed -i 's%----ADMIN_TOKEN----%${{ secrets.ADMIN_TOKEN }}%g' vault.container
      - name: Configure service SMTP_PASSWORD
        run: sed -i 's%----SMTP_PASSWORD----%${{ secrets.SMTP_PASSWORD }}%g' vault.container
      - name: Configure service DATABASE_PASSWORD
        run: sed -i 's%----DATABASE_PASSWORD----%${{ secrets.DATABASE_PASSWORD }}%g' vault.container
      - name: Configure service YUBICO_SECRET_KEY
        run: sed -i 's%----YUBICO_SECRET_KEY----%${{ secrets.YUBICO_SECRET_KEY }}%g' vault.container
      - name: Configure service proxy
        run: mkdir proxy.container.d; mv proxy.conf proxy.container.d/vault.conf
      - name: Make service directory
        run: ssh service@${{ matrix.host }} mkdir -p /home/service/.config/containers/systemd/vault
      - name: deploy service
        run: rsync -v -p -r * service@${{ matrix.host }}:/home/service/.config/containers/systemd/vault
      - name: load service
        run: ssh service@${{ matrix.host }} systemctl --user daemon-reload
      - name: start service
        run: ssh service@${{ matrix.host }} systemctl --user restart vault-volume vault
      - name: start service proxy
        run: ssh service@${{ matrix.host }} systemctl --user restart proxy